/**
 * This file is part of the Sandy Andryanto Blog Application.
 *
 * @author     Sandy Andryanto <sandy.andryanto.blade@gmail.com>
 * @copyright  2025
 *
 * For the full copyright and license information,
 * please view the LICENSE.md file that was distributed
 * with this source code.
 */

namespace backend.Models
{
    public class JobTitle
    {
        public static List<String> GetData()
        {
            return new List<string> {
                 "accountant",
                  "actor",
                  "actuary",
                  "adhesive bonding machine tender",
                  "adjudicator",
                  "administrative assistant",
                  "administrative services manager",
                  "adult education teacher",
                  "advertising manager",
                  "advertising sales agent",
                  "aerobics instructor",
                  "aerospace engineer",
                  "aerospace engineering technician",
                  "agent",
                  "agricultural engineer",
                  "agricultural equipment operator",
                  "agricultural grader",
                  "agricultural inspector",
                  "agricultural manager",
                  "agricultural sciences teacher",
                  "agricultural sorter",
                  "agricultural technician",
                  "agricultural worker",
                  "air conditioning installer",
                  "air conditioning mechanic",
                  "air traffic controller",
                  "aircraft cargo handling supervisor",
                  "aircraft mechanic",
                  "aircraft service technician",
                  "airline copilot",
                  "airline pilot",
                  "ambulance dispatcher",
                  "ambulance driver",
                  "amusement machine servicer",
                  "anesthesiologist",
                  "animal breeder",
                  "animal control worker",
                  "animal scientist",
                  "animal trainer",
                  "animator",
                  "answering service operator",
                  "anthropologist",
                  "apparel patternmaker",
                  "apparel worker",
                  "arbitrator",
                  "archeologist",
                  "architect",
                  "architectural drafter",
                  "architectural manager",
                  "archivist",
                  "art director",
                  "art teacher",
                  "artist",
                  "assembler",
                  "astronomer",
                  "athlete",
                  "athletic trainer",
                  "ATM machine repairer",
                  "atmospheric scientist",
                  "attendant",
                  "audio and video equipment technician",
                  "audio-visual and multimedia collections specialist",
                  "audiologist",
                  "auditor",
                  "author",
                  "auto damage insurance appraiser",
                  "automotive and watercraft service attendant",
                  "automotive glass installer",
                  "automotive mechanic",
                  "avionics technician",
                  "back-end developer",
                  "baggage porter",
                  "bailiff",
                  "baker",
                  "barback",
                  "barber",
                  "bartender",
                  "basic education teacher",
                  "behavioral disorder counselor",
                  "bellhop",
                  "bench carpenter",
                  "bicycle repairer",
                  "bill and account collector",
                  "billing and posting clerk",
                  "biochemist",
                  "biological technician",
                  "biomedical engineer",
                  "biophysicist",
                  "blaster",
                  "blending machine operator",
                  "blockmason",
                  "boiler operator",
                  "boilermaker",
                  "bookkeeper",
                  "boring machine tool tender",
                  "brazer",
                  "brickmason",
                  "bridge and lock tender",
                  "broadcast news analyst",
                  "broadcast technician",
                  "brokerage clerk",
                  "budget analyst",
                  "building inspector",
                  "bus mechanic",
                  "butcher",
                  "buyer",
                  "cabinetmaker",
                  "cafeteria attendant",
                  "cafeteria cook",
                  "camera operator",
                  "camera repairer",
                  "cardiovascular technician",
                  "cargo agent",
                  "carpenter",
                  "carpet installer",
                  "cartographer",
                  "cashier",
                  "caster",
                  "ceiling tile installer",
                  "cellular equipment installer",
                  "cement mason",
                  "channeling machine operator",
                  "chauffeur",
                  "checker",
                  "chef",
                  "chemical engineer",
                  "chemical plant operator",
                  "chemist",
                  "chemistry teacher",
                  "chief executive",
                  "child social worker",
                  "childcare worker",
                  "chiropractor",
                  "choreographer",
                  "civil drafter",
                  "civil engineer",
                  "civil engineering technician",
                  "claims adjuster",
                  "claims examiner",
                  "claims investigator",
                  "cleaner",
                  "clinical laboratory technician",
                  "clinical laboratory technologist",
                  "clinical psychologist",
                  "coating worker",
                  "coatroom attendant",
                  "coil finisher",
                  "coil taper",
                  "coil winder",
                  "coin machine servicer",
                  "commercial diver",
                  "commercial pilot",
                  "commodities sales agent",
                  "communications equipment operator",
                  "communications teacher",
                  "community association manager",
                  "community service manager",
                  "compensation and benefits manager",
                  "compliance officer",
                  "composer",
                  "computer hardware engineer",
                  "computer network architect",
                  "computer operator",
                  "computer programmer",
                  "computer science teacher",
                  "computer support specialist",
                  "computer systems administrator",
                  "computer systems analyst",
                  "concierge",
                  "conciliator",
                  "concrete finisher",
                  "conservation science teacher",
                  "conservation scientist",
                  "conservation worker",
                  "conservator",
                  "construction inspector",
                  "construction manager",
                  "construction painter",
                  "construction worker",
                  "continuous mining machine operator",
                  "convention planner",
                  "conveyor operator",
                  "cook",
                  "cooling equipment operator",
                  "copy marker",
                  "correctional officer",
                  "correctional treatment specialist",
                  "correspondence clerk",
                  "correspondent",
                  "cosmetologist",
                  "cost estimator",
                  "costume attendant",
                  "counseling psychologist",
                  "counselor",
                  "courier",
                  "court reporter",
                  "craft artist",
                  "crane operator",
                  "credit analyst",
                  "credit checker",
                  "credit counselor",
                  "criminal investigator",
                  "criminal justice teacher",
                  "crossing guard",
                  "curator",
                  "custom sewer",
                  "customer service representative",
                  "cutter",
                  "cutting machine operator",
                  "dancer",
                  "data entry keyer",
                  "database administrator",
                  "decorating worker",
                  "delivery services driver",
                  "demonstrator",
                  "dental assistant",
                  "dental hygienist",
                  "dental laboratory technician",
                  "dentist",
                  "dermatologist",
                  "derrick operator",
                  "designer",
                  "desktop publisher",
                  "detective",
      "developer",
      "diagnostic medical sonographer",
      "die maker",
      "diesel engine specialist",
      "dietetic technician",
      "dietitian",
      "dinkey operator",
      "director",
      "dishwasher",
      "dispatcher",
      "DJ",
      "doctor",
      "door-to-door sales worker",
      "drafter",
      "dragline operator",
      "drama teacher",
      "dredge operator",
      "dressing room attendant",
      "dressmaker",
      "drier operator",
      "drilling machine tool operator",
      "dry-cleaning worker"
            };
        }
    }
}
